os: linux
# see https://docs.travis-ci.com/user/reference/xenial/
dist: xenial
language: clojure
lein: 2.7.1
jdk:
  - openjdk8
# see https://docs.travis-ci.com/user/build-stages/
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      script:
        - lein clj-kondo-lint
        - lein test
        - lein test :generative
        - lein with-profile dev,recent-clj test
    - stage: deploy
      script: lein deploy clojars
      #see https://docs.travis-ci.com/user/conditions-v1
      if: fork = false AND tag =~ ^(\d+)\.(\d+)\.(\d+)(-.+)?$
